# Generated by Django 3.1.2 on 2020-11-01 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(max_length=250, verbose_name='Link')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('alterado', models.DateTimeField(auto_now=True, verbose_name='Alterado')),
                ('status', models.CharField(choices=[('publicado', 'Pulbicado'), ('rascunho', 'Rascunho')], default='rascunho', max_length=10, verbose_name='Status')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria', models.ManyToManyField(related_name='get_pots', to='blog.Category', verbose_name='Categoria')),
            ],
            options={
                'ordering': ('-publicado',),
            },
        ),
    ]
