# Generated by Django 3.1.2 on 2020-11-01 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201101_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Sub-Título'),
            preserve_default=False,
        ),
    ]
